import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Facebook, Instagram, Twitter, Youtube } from "lucide-react";
import { Metadata } from "next";
import Link from "next/link";
import MapView from "../_components/map-view";
import WhatsAppIcon from "@/public/whatsapp-icon.svg";
import Image from "next/image";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Beauty Salon | İletişim",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <h3 className="text-2xl">İletişim</h3>
      <div className="grid md:grid-cols-4 gap-5 my-5">
        <Card className="md:col-span-2">
          <CardHeader>
            <CardTitle>İletişim Bilgileri</CardTitle>
          </CardHeader>
          <CardContent className="space-y-5">
            <p>
              <strong>Adres:</strong> İstasyon Mahallesi, 140. Sokak, No: 1,
              27000 Gaziantep
            </p>
            <p>
              <strong>Telefon:</strong> 0 (342) 220 00 00
            </p>
            <p>
              <strong>E-Posta:</strong>
              <a href="mailto:mail@mail.com">
                <span className="ml-1">mail@mail.com</span>
              </a>
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Hızlı İletişim</CardTitle>
            <CardDescription>
              Hızlı geri dönüşler için Whatsapp&apos;tan yazabilirsiniz
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-5 flex items-center justify-center">
            <Button asChild className="w-full">
              <Link href="" className="flex items-center gap-2">
                <Image
                  src={WhatsAppIcon}
                  alt="WhatsApp"
                  width={64}
                  height={64}
                />
                <span>Whatsapp</span>
              </Link>
            </Button>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Sosyal Medya</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex space-x-5">
              <Link
                href="https://www.facebook.com/"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center justify-center w-10 h-10 rounded-full bg-gray-200"
              >
                <Facebook className="text-2xl text-gray-500" />
              </Link>
              <Link
                href="https://www.twitter.com/"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center justify-center w-10 h-10 rounded-full bg-gray-200"
              >
                <Twitter className="text-2xl text-gray-500" />
              </Link>
              <Link
                href="https://www.instagram.com/"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center justify-center w-10 h-10 rounded-full bg-gray-200"
              >
                <Instagram className="text-2xl text-gray-500" />
              </Link>
              <Link
                href="https://www.youtube.com/"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center justify-center w-10 h-10 rounded-full bg-gray-200"
              >
                <Youtube className="text-2xl text-gray-500" />
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
      <MapView />
    </div>
  );
}
