import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Beauty Salon | Profilim",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <h3 className="text-xl">Profilim</h3>
      <div className="mt-5 space-y-5">
        <Input placeholder="Ad Soyad" />
        <Input disabled placeholder="Email" />
        <Input placeholder="Telefon" />
        <Textarea placeholder="Not" />
        <Button>Değişiklikleri Kaydet</Button>
      </div>
    </div>
  );
}
