import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Beauty Salon | Hakkımızda",
  description: "Generated by create next app",
};

export default function Page() {
  return <div>Hakkımızda</div>;
}
